default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: ':rotating_light: auto fix by pre-commit hooks'
  autofix_prs: true
  autoupdate_branch: main
  autoupdate_schedule: monthly
  autoupdate_commit_msg: ':arrow_up: auto update by pre-commit hooks'

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
